Improve UI/UX on user homepage
azaria-dedmon/covid-19 pull request #63
Opened 2021-03-12 05:25 UTC by azaria-dedmon

**What does this PR do?**

- This PR makes improvements to the user homepage.

**Description of task to be completed.**

- Improve symmetry of elements on page.
- Remove unnecessary links
- Add new link to navbar.
- Improve search bar.

**How should this be manually tested?**

- This does not have to be tested.

2021-03-12 07:56 UTC, alexkayabula commented
@azaria-dedmon change the title to `Improve UI/UX for the user page`

2021-03-12 07:57 UTC, alexkayabula commented
The font used int the user page should be the same as the one used in the homepage.

2021-03-12 07:57 UTC, alexkayabula commented
The navbar is missing a link or icon to the homepage.

2021-03-12 07:59 UTC, alexkayabula commented
The navbar link `review testing site` should be `review testing sites`.

2021-03-12 15:50 UTC, azaria-dedmon commented
@alexkayabula For the homepage, I used Bootstrap's Jumbotron div. Therefore I am not certain about the type of font that was used. However, I've compared the two pages to one another and they look the exact same to me. I cannot tell the difference.

2021-03-13 02:48 UTC, alexkayabula requested changes

2021-03-13 02:48 UTC, alexkayabula commented on app/templates/location.html
> +            <li><a href="/">Homepage</a></li>
@azaria-dedmon rename the Homepage link to Home and it should appear before the My Dashboard link in the navbar.

2021-03-13 02:48 UTC, alexkayabula commented on app/templates/base.html
> +      <li><a href="/">Homepage</a></li>
@azaria-dedmon rename the Homepage link to Home and it should appear before the My Dashboard link in the navbar.

2021-03-13 02:48 UTC, alexkayabula commented on app/templates/users/user_edit.html
> +            <li><a href="/user">My Dashboard</a></li>
This should be under a different PR. We are improving the UI/UX of the user page.

2021-03-13 02:51 UTC, alexkayabula commented
> @alexkayabula For the homepage, I used Bootstrap's Jumbotron div. Therefore I am not certain about the type of font that was used. However, I've compared the two pages to one another and they look the exact same to me. I cannot tell the difference.

You can also use Bootstraps Jumbotron for the userpage so that the UI looks consistent.

2021-03-13 04:32 UTC, alexkayabula commented on app/templates/base.html
>          <input class="search" type="text" name="username" placeholder="Search username">
Change the Place holder to "Enter Username"

2021-03-13 04:35 UTC, alexkayabula commented on app/templates/base.html
> +        <input id="search-btn"class="search" type="submit" value="search">
Change the value to "Search"

2021-03-13 15:48 UTC, azaria-dedmon commented
> > @alexkayabula For the homepage, I used Bootstrap's Jumbotron div. Therefore I am not certain about the type of font that was used. However, I've compared the two pages to one another and they look the exact same to me. I cannot tell the difference.
> 
> You can also use Bootstraps Jumbotron for the userpage so that the UI looks consistent.

I cannot use Bootstraps "Jumbotron" feature as a small div. It is a hero styled banner; it's not suppose to be small in width. If I were to use it for the bottom two divs, they would both be as wide as the top banner.

2021-03-13 15:49 UTC, azaria-dedmon commented
@alexkayabula Please disregard the previous comment.

2021-03-13 20:45 UTC, alexkayabula commented
@azaria-dedmon I am going to look into this later on in the day, I am occupied at the moment. I will get back to you as soon as I am done reviewing. Thanx

2021-03-13 20:58 UTC, azaria-dedmon commented
> @azaria-dedmon I am going to look into this later on in the day, I am occupied at the moment. I will get back to you as soon as I am done reviewing. Thanx

Okay. Thanks for the update.

2021-03-14 06:30 UTC, alexkayabula reviewed
@azaria-dedmon I have made some improvements to this PR. Please review, test out the changes and confirm then I can merge.

2021-03-14 12:33 UTC, azaria-dedmon commented
> @azaria-dedmon I have made some improvements to this PR. Please review, test out the changes and confirm then I can merge.

I made a mistake and did not merge the commits that you made. I liked the changes, but decided to switch the default photo for another pic. If you could, please push those changes back to the branch. Sorry for the inconvenience.

2021-03-14 22:34 UTC, closed without merging