Improve UI/UX on Location Map page
azaria-dedmon/covid-19 pull request #65
Opened 2021-03-15 05:10 UTC by azaria-dedmon

2021-03-15 12:34 UTC, alexkayabula commented
@azaria-dedmon fix the search option in the resulting`navbar` accordingly.

2021-03-15 16:02 UTC, azaria-dedmon commented
> @azaria-dedmon fix the search option in the resulting`navbar` accordingly.

Okay.

2021-03-16 05:01 UTC, alexkayabula requested changes

2021-03-16 05:01 UTC, alexkayabula commented on app/templates/location.html
> +            <input class="search-btn" type="submit" value="search">
@azaria-dedmon `search` should be capitalized. Also make sure the search button is exactly the same width as the search field.

2021-03-16 06:10 UTC, alexkayabula approved these changes
LGTM.Thank you.

2021-03-16 06:10 UTC, merged